{% set name = "pocr" %}
{% set version = "0.1.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/lvoegtlin/pocr.git
  git_tag: master

build:
  number: 0
  entry_points:
    - pocr=pocr.controller:entry_point
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  always_include_files:
    - pocr/conf/vcs.yml
    - pocr/utils/pre-commit

requirements:
  host:
    - gitpython ==3.0.3
    - keyring ==19.0.1
    - pip
    - prompt_toolkit ==1.0.14
    - pygithub ==1.43.6
    - pyinquirer ==1.0.3
    - python
    - pyyaml ==5.1.2
    - tabulate ==0.8.5
    - readme-renderer>=21.0
    - setuptools
  run:
    - gitpython ==3.0.3
    - keyring ==19.0.1
    - prompt_toolkit ==1.0.14
    - pygithub ==1.43.6
    - pyinquirer ==1.0.3
    - python
    - pyyaml ==5.1.2
    - tabulate ==0.8.5
    - readme-renderer>=21.0
    - setuptools

test:
  imports:
    - pocr
    - pocr.conf
    - pocr.utils
  commands:
    - pocr --help

about:
  home: "https://github.com/lvoegtlin/pocr"
  license: "MIT"
  license_family: "MIT"
  license_file: ""
  summary: "A tool to create and maintain your python projects"
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - lvoegtlin
