#!/bin/sh

export_env () {
    # export the environment again
    echo "\nExporting environment ${CONDA_DEFAULT_ENV}...\n"
    conda env export > environment.yml
    exit 0
}

wrong_env () {
     echo "\nThe base environment or no environment is active.\n"
    echo "Activate the fitting environment and commit again!"
    exit 1
}

FILE=environment.yml
if [[ ! -f ${FILE} ]];
then
    echo "No environment.yml file found.\n"
    echo "Please navigate into the root directory of your project and commit again."
    exit 1
fi


# get the first line of the current environment file
line=$(head -n 1 ${FILE})

if [[ ${line} = "" ]];
then
    if [[ ${CONDA_DEFAULT_ENV} != "base" ]];
    then
        export_env
    else
        wrong_env
    fi
fi


env_name=$(echo ${line} | sed 's/^name: \(.*\)$/\1/')

# check if the active environment is the same as the environment file
if [[ ${CONDA_DEFAULT_ENV} = ${env_name} ]];
then
    export_env
else
    wrong_env
fi
